/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package edu.progavud.taller1.View;

import edu.progavud.taller1.control.ControlVentana;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ACER NITRO
 */
public class PanelMantenimiento extends JPanel {
    private ControlVentana controlVentana;
    public PanelMantenimiento() {
        initComponents();
        setVisible(true);
        add(new JLabel("JSDFJASJDFJASDJFJASJ"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");


        jPanel1.setBackground(new java.awt.Color(236, 133, 37));

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 233, 220));
        jLabel1.setText("¡¡LO SENTIMOS!! ");
        add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 233, 220));
        jLabel2.setText("Esta página esta en desarrollo...");
        add(jLabel2);

        jButton1.setBackground(new java.awt.Color(35, 206, 61));
        jButton1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 233, 220));
        jButton1.setText("MENU");
        jButton1.setName("botonMenu"); // NOI18N
        add(jButton1);

        jButton2.setBackground(new java.awt.Color(231, 43, 43));
        jButton2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(242, 233, 220));
        jButton2.setText("SALIR");
        jButton2.setName("botonSalir"); // NOI18N
        add(jButton2);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/hamburguesa/img0.png"))); // NOI18N
        add(jLabel5);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1165, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public JButton getjButton1() {
        return jButton1;
    }

    public void setjButton1(JButton jButton1) {
        this.jButton1 = jButton1;
    }

    public JButton getjButton2() {
        return jButton2;
    }

    public void setjButton2(JButton jButton2) {
        this.jButton2 = jButton2;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }
}
